# Generated by Django 4.1.1 on 2022-09-12 19:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id_catalog', models.AutoField(primary_key=True, serialize=False, verbose_name='ID каталога')),
                ('catalog', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Категория товаров')),
                ('slug_catalog', models.SlugField(default='', unique=True, verbose_name='ЧПУ каталога')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID товара')),
                ('good', models.CharField(db_index=True, max_length=50, verbose_name='Название товара')),
                ('slug_product', models.SlugField(default='', unique=True, verbose_name='ЧПУ товара')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('discount', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=7, null=True, verbose_name='Скидочная цена')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('reviews', models.CharField(blank=True, max_length=500, verbose_name='Отзывы')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание товара')),
                ('images', models.FileField(upload_to='product_pictures', verbose_name='Фото товара')),
                ('parent_catalog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.productcatalog', verbose_name='Родительский каталог')),
            ],
        ),
    ]
