# Generated by Django 4.1.1 on 2022-09-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_product',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID товара'),
        ),
    ]
