# Generated by Django 4.1.1 on 2023-01-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почтовый адрес')),
                ('topic', models.CharField(max_length=70, verbose_name='Тема обращения')),
                ('review', models.CharField(max_length=500, verbose_name='Отзыв')),
            ],
        ),
    ]
